kind: ConfigMap
apiVersion: v1
metadata:
  name: trustify-dumps-import-config
  labels:
    app.kubernetes.io/name: trustify-dumps-import-config
    app.kubernetes.io/component: create-dump
    app.kubernetes.io/part-of: trustify-dumps

data:
  input.yaml: |
    $schema: xtask/schema/generate-dump.json
    import:
      - !sbom
        description: All Red Hat SBOMs
        source: https://access.redhat.com/security/data/sbom/beta/
        period: 1s
        fetchRetries: 50
        keys:
          - https://access.redhat.com/security/data/97f5eac4.txt#77E79ABE93673533ED09EBE2DCE3823597F5EAC4

      - !csaf
        description: All Red Hat advisories
        source: redhat.com
        period: 1s
        fetchRetries: 50

      - !cve
        description: All CVEs
        source: https://github.com/CVEProject/cvelistV5
        period: 1s
