kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: trustify-dumps
  labels:
    app.kubernetes.io/name: trustify-dumps
    app.kubernetes.io/component: create-dump
    app.kubernetes.io/part-of: trustify-dumps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
